uploadImage/uploadImage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('uploadModel/', include('uploadModel.urls')),
]

uploadImage/uploadModel/urls.py
from django.urls import path
from . import views
app_name = 'uploadModel'
urlpatterns = [
    path('', views.uploadFile),
    path('getFile/', views.getFile, name = 'getFile')
]

uploadImage/uploadModel/models.py
from django.db import models

# Create your models here.

class UpForm(models.Model):
    image2 = models.FileField()

uploadImage/uploadModel/forms.py
from django import forms

class UploadFileForm(forms.Form):
    image1 = forms.FileField()

uploadImage/uploadModel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import UpForm
from .forms import UploadFileForm
# Create your views here.
def uploadFile(request):
    UF = UploadFileForm
    return render(request, 'uploadModel/fileUpload.html', {'UF': UF})

def getFile(request):
    form = UploadFileForm(request.POST, request.FILES)
    if form.is_valid():
        instance = UpForm(image2=request.FILES["image1"])
        instance.save()
        return HttpResponse("save file success")

uploadImage/uploadModel/templates/uploadModel/fileUpload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload File</title>
</head>
<body>
    <h2>Upload File Here</h2>
    <form action="{% url 'uploadModel:getFile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{UF.as_p}}
        <input type="submit">
    </form>
    
</body>
</html>